import pathlib, io

lines = []
lines += [""]
lines += [""]
lines += ["# ============================================================"]
lines += ["# 10.5  MCP SERVER  (VS Code Copilot / Cursor / Antigravity)"]
lines += ["# ============================================================"]
lines += [""]
lines += ["_MCP_TOOLS: list[dict] = ["]
lines += ["    {"]
lines += ["        \"name\": \"codevx_submit_order\","]
lines += ["        \"description\": \"Submit a task to the CoDevx 8-agent SDLC pipeline.\","]
lines += ["        \"inputSchema\": {"]
lines += ["            \"type\": \"object\","]
lines += ["            \"properties\": {\"task\": {\"type\": \"string\", \"description\": \"Feature to build\"}},"]
lines += ["            \"required\": [\"task\"],"]
lines += ["        },"]
lines += ["    },"]
lines += ["    {\"name\": \"codevx_get_state\", \"description\": \"Get all agent statuses.\", \"inputSchema\": {\"type\": \"object\", \"properties\": {}}},"]
lines += ["    {\"name\": \"codevx_get_history\", \"description\": \"List completed tasks.\", \"inputSchema\": {\"type\": \"object\", \"properties\": {}}},"]
lines += ["    {"]
lines += ["        \"name\": \"codevx_get_logs\","]
lines += ["        \"description\": \"Get recent pipeline logs.\","]
lines += ["        \"inputSchema\": {\"type\": \"object\", \"properties\": {\"limit\": {\"type\": \"integer\", \"default\": 50}}},"]
lines += ["    },"]
lines += ["    {"]
lines += ["        \"name\": \"codevx_get_agent\","]
lines += ["        \"description\": \"Get status of a specific agent by name.\","]
lines += ["        \"inputSchema\": {\"type\": \"object\", \"properties\": {\"name\": {\"type\": \"string\", \"enum\": [\"Project Manager\", \"Architect\", \"Frontend Dev\", \"Backend Dev\", \"QA Engineer\", \"DevOps Engineer\", \"Security Analyst\", \"Database Engineer\"]}}, \"required\": [\"name\"]},"]
lines += ["    },"]
lines += ["]"]
lines += [""]
lines += ["_MCP_SERVER_INFO: dict = {"]
lines += ["    \"protocolVersion\": \"2024-11-05\","]
lines += ["    \"serverInfo\": {\"name\": \"codevx\", \"version\": \"5.0.0\"},"]
lines += ["    \"capabilities\": {\"tools\": {}},"]
lines += ["}"]
lines += [""]
lines += [""]
lines += ["@app.get(\"/mcp\")"]
lines += ["async def mcp_capabilities() -> dict:"]
lines += ["    return _MCP_SERVER_INFO"]
lines += [""]
lines += [""]
lines += ["@app.post(\"/mcp\")"]
lines += ["async def mcp_dispatch(request: Request) -> dict:  # noqa: C901"]
lines += ["    body: dict = await request.json()"]
lines += ["    rpc_id = body.get(\"id\")"]
lines += ["    method: str = body.get(\"method\", \"\")"]
lines += ["    params: dict = body.get(\"params\") or {}"]
lines += [""]
lines += ["    def _ok(result: object) -> dict:"]
lines += ["        return {\"jsonrpc\": \"2.0\", \"id\": rpc_id, \"result\": result}"]
lines += [""]
lines += ["    def _err(code: int, msg: str) -> dict:"]
lines += ["        return {\"jsonrpc\": \"2.0\", \"id\": rpc_id, \"error\": {\"code\": code, \"message\": msg}}"]
lines += [""]
lines += ["    try:"]
lines += ["        if method == \"initialize\":"]
lines += ["            return _ok(_MCP_SERVER_INFO)"]
lines += [""]
lines += ["        if method == \"tools/list\":"]
lines += ["            return _ok({\"tools\": _MCP_TOOLS})"]
lines += [""]
lines += ["        if method == \"tools/call\":"]
lines += ["            tool: str = params.get(\"name\", \"\")"]
lines += ["            args: dict = params.get(\"arguments\") or {}"]
lines += [""]
lines += ["            if tool == \"codevx_submit_order\":"]
lines += ["                task = str(args.get(\"task\", \"\")).strip()"]
lines += ["                if not task:"]
lines += ["                    return _err(-32602, \"task argument is required\")"]
lines += ["                import uuid as _u; tid = str(_u.uuid4())[:8]"]
lines += ["                add_log(f\"[MCP] Order via IDE task_id={tid}\")"]
lines += ["                SYSTEM_STATE[\"current_task\"] = task"]
lines += ["                asyncio.create_task(execute_pipeline(None, task))"]
lines += ["                return _ok({\"content\": [{\"type\": \"text\", \"text\": f\"Order submitted tid={tid} -- Pipeline started\"}]})"]
lines += [""]
lines += ["            if tool == \"codevx_get_state\":"]
lines += ["                return _ok({\"content\": [{\"type\": \"text\", \"text\": json.dumps(SYSTEM_STATE, indent=2)}]})"]
lines += [""]
lines += ["            if tool == \"codevx_get_history\":"]
lines += ["                return _ok({\"content\": [{\"type\": \"text\", \"text\": json.dumps(SYSTEM_STATE[\"history\"], indent=2)}]})"]
lines += [""]
lines += ["            if tool == \"codevx_get_logs\":"]
lines += ["                lim = max(1, min(int(args.get(\"limit\", 50)), 200))"]
lines += ["                return _ok({\"content\": [{\"type\": \"text\", \"text\": chr(10).join(SYSTEM_STATE[\"logs\"][-lim:])}]})"]
lines += [""]
lines += ["            if tool == \"codevx_get_agent\":"]
lines += ["                nm = str(args.get(\"name\", \"\"))"]
lines += ["                ag = SYSTEM_STATE[\"agents\"].get(nm)"]
lines += ["                if not ag:"]
lines += ["                    return _err(-32602, f\"Agent not found: {nm}\")"]
lines += ["                return _ok({\"content\": [{\"type\": \"text\", \"text\": json.dumps({\"name\": nm, **ag}, indent=2)}]})"]
lines += [""]
lines += ["            return _err(-32601, f\"Unknown tool: {tool}\")"]
lines += [""]
lines += ["        if method == \"ping\":"]
lines += ["            return _ok({})"]
lines += [""]
lines += ["        return _err(-32601, f\"Unknown method: {method}\")"]
lines += [""]
lines += ["    except Exception as exc:"]
lines += ["        add_log(f\"[MCP][ERROR] {exc}\")"]
lines += ["        return _err(-32603, \"Internal MCP server error\")"]
lines += [""]
lines += [""]

mcp_block = chr(10).join(lines)

p = pathlib.Path("agent_mesh.py")
text = p.read_text(encoding="utf-8")

ANCHOR = "@app.get(\"/\", response_class=HTMLResponse)"
assert ANCHOR in text
text = text.replace(ANCHOR, mcp_block + ANCHOR, 1)

OLD_B = "    print(\"  API Docs:   http://localhost:8000/docs\")"
NEW_B = "    print(\"  MCP Server: http://localhost:8000/mcp\")" + chr(10) + OLD_B
if "MCP Server" not in text:
    text = text.replace(OLD_B, NEW_B, 1)

p.write_text(text, encoding="utf-8")
print("Done.")
